name: Test OSQP Matlab Interface

on: [push, pull_request]

jobs:
  build:
    # As of May 28, 2021 Matlab isn't able to be used on Windows or Linux on GitHub shared runners
    # (it errors saying the dependencies aren't available on those platforms). Instead we can only
    # test on ubuntu-latest. The matrix below is preserved here in case Matlab support is added
    # to those other platforms.
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]

#    runs-on: ${{ matrix.os }}
    runs-on: self-hosted

    defaults:
      run:
        shell: bash -l {0}
          
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: false

      - name: Check out submodules recursively
        run: |
          pwd
          ls -la

      - name: Check MATLAB
        run: |
          echo $SHELL
          echo $PATH
          which matlab


